Repository PawelDabrowski83/genAlgo, pull requests merged in 2021-01, with the labels that each got.

#55 description of CrossoverService
  README.md
Labels: documentation

#59 added description of Gene.setValue and refactor of Gene class descrip…
  README.md
Labels: documentation

#62 documentation for Gene class
  README.md
  images/Gene-s4.png
Labels: documentation

#63 CrossoverService - docs update with pictures
  README.md
  images/CrossoverService-s4.png
Labels: documentation

#67 CrossoverService docs fix
  README.md
Labels: documentation

#77 71 mutator docs
  README.md
  images/MutatorService-s5.png
  images/genAlgo-s5.png
Labels: documentation

#78 Change Gene.generateValue return type to char. Assign this.value with…
  src/main/java/com/facebook/genAlgo/gene/Gene.java
Labels: enhancement

#87 Add headings for description of each section in Code structure chapter.
  README.md
Labels: documentation, enhancement

#85 80 bitwise should throw exceptions
  src/main/java/com/facebook/genAlgo/utils/BitwiseUtils.java
Labels: enhancement

#88 79 remove images
  images/genAlgo-s5.png
  images/genAlgo-stage1.jpg
  images/genAlgo-stage2.png
  images/genAlgo-stage3-update.png
  images/genAlgo-stage3.png
Labels: enhancement

#89 70 better names for evaluators
  src/main/java/com/facebook/genAlgo/evaluator/LogarithmicEvaluatorImpl.java
  src/main/java/com/facebook/genAlgo/evaluator/MaxDeltaEvaluatorImpl.java
  src/test/java/com/facebook/genAlgo/evaluator/LogarithmicEvaluatorImplTest.java
  src/test/java/com/facebook/genAlgo/evaluator/MaxDeltaEvaluatorImplTest.java
Labels: enhancement

#92 Create LICENSE
  LICENSE
Labels: documentation

#90 83 random provider get float
  src/main/java/com/facebook/genAlgo/gene/Gene.java
  src/main/java/com/facebook/genAlgo/utils/RandomProvider.java
  src/main/java/com/facebook/genAlgo/utils/RandomProviderImpl.java
  src/test/java/com/facebook/genAlgo/evaluator/LogarithmicEvaluatorImplTest.java
  src/test/java/com/facebook/genAlgo/evaluator/MaxDeltaEvaluatorImplTest.java
  src/test/java/com/facebook/genAlgo/gene/GeneTest.java
Labels: enhancement

#96 91 random provider docs
  README.md
  images/Gene-s4.png
  images/Gene-s5.png
  images/RandomProvider-s5.png
Labels: documentation, enhancement

#99 Move Mutator headline to the beginning of Mutator description in Code…
  README.md
Labels: documentation, enhancement

#98 84 bitwise utils docs
  README.md
  images/BitwiseUtils-s5.png
  images/class-connection-diagram2-s5.png
Labels: documentation

#103 102 mutator refactor
  src/main/java/com/facebook/genAlgo/mutator/MultipleMutator.java
  src/main/java/com/facebook/genAlgo/mutator/SingleMutator.java
  src/test/java/com/facebook/genAlgo/mutator/MultipleMutatorTest.java
  src/test/java/com/facebook/genAlgo/mutator/SingleMutatorTest.java
Labels: enhancement

#110 107 gene pool docs
  README.md
  images/GenePool-s6.png
Labels: documentation

#117 Add description of Stage 7 workplan.
  README.md
Labels: documentation

#118 105 random provider get int from range
  src/main/java/com/facebook/genAlgo/mutator/MultipleMutator.java
  src/main/java/com/facebook/genAlgo/utils/RandomProvider.java
  src/main/java/com/facebook/genAlgo/utils/RandomProviderImpl.java
  src/test/java/com/facebook/genAlgo/mutator/MultipleMutatorTest.java
Labels: enhancement
