Repository PawelDabrowski83/genAlgo, pull requests merged in 2021-03, with the labels that each got.

#191 153 gene pool docs update
  README.md
Labels: documentation

#210 Add assertion to shouldReturnListOfGeneWithTargetValue method
  src/test/java/com/facebook/genAlgo/MainIntegrationTest.java
Labels: enhancement

#219 Add empty line to fix commit.
  README.md
Labels: documentation

#217 Add stage 14 description.
  README.md
Labels: documentation

#215 213 mutator docs update
  README.md
Labels: documentation, enhancement

#218 195 evaluator factory docs
  README.md
Labels: documentation, enhancement

#225 224 mutator factory impl refactor
  src/main/java/com/facebook/genAlgo/mutator/MutatorFactory.java
Labels: enhancement
